### ISSUE TITLE
Fix schedule display

### ISSUE THREAD

**Issue by nelsonmestevao** [cesium/codeweek18#4]
At this moment, the schedule shows every event and then once you star navigating through the left menu it would start display correctly.

Fixed by #13.

**Comment by hellypi** [comment]
Quando clico em qualquer parte no schedule recebo este erro no terminal

`[2018-09-26 15:35:25] ERROR '/assets/js/popper.min.js.map' not found.`
`[2018-09-26 15:35:25] ERROR '/assets/js/bootstrap.min.js.map' not found.`

Mas quando abro a pasta _site/assets/js os ficheiros estão lá. Sabes porque é que isto acontece?

**Comment by nelsonmestevao** [comment]
> Quando clico em qualquer parte no schedule recebo este erro no terminal
> 
> `[2018-09-26 15:35:25] ERROR '/assets/js/popper.min.js.map' not found.`
> `[2018-09-26 15:35:25] ERROR '/assets/js/bootstrap.min.js.map' not found.`
> 
> Mas quando abro a pasta _site/assets/js os ficheiros estão lá. Sabes porque é que isto acontece?

Não consegui reproduzir esse erro. Tens a tua branch atualizada?
